### ISSUE TITLE
Few tests fail

### ISSUE THREAD

**Issue by yurivict** [dwavesystems/dwave-inspector#151]
```
======================================================================
ERROR: test_failure (tests.test_proxies.TestProxies)
Next rewriter (by priority) is retried on failure.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/ports/science/py-dwave-inspector/work-py39/dwave-inspector-0.4.0/dwave/inspector/utils.py", line 154, in wrapper
    return fn(*args, **kwargs)
  File "/usr/ports/science/py-dwave-inspector/work-py39/dwave-inspector-0.4.0/tests/test_proxies.py", line 74, in test_failure
    self.assertEqual(rewrite_url(url), f'proxy://{url}')
  File "/usr/ports/science/py-dwave-inspector/work-py39/dwave-inspector-0.4.0/dwave/inspector/proxies.py", line 74, in rewrite_url
    for rewriter in prioritized_url_rewriters():
  File "/usr/ports/science/py-dwave-inspector/work-py39/dwave-inspector-0.4.0/dwave/inspector/proxies.py", line 64, in prioritized_url_rewriters
    proxies = [ep.load() for ep in entry_points().select(group=entry_point_group['proxies'])]
  File "/usr/local/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 1019, in entry_points
    return SelectableGroups.load(eps).select(**params)
  File "/usr/local/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 472, in load
    ordered = sorted(eps, key=by_group)
  File "/usr/local/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 1016, in <genexpr>
    eps = itertools.chain.from_iterable(
  File "/usr/local/lib/python3.9/site-packages/importlib_metadata/_itertools.py", line 16, in unique_everseen
    k = key(element)
AttributeError: 'InMemoryDistribution' object has no attribute '_normalized_name'

======================================================================
ERROR: test_rewrite (tests.test_proxies.TestProxies)
URL rewritten.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/ports/science/py-dwave-inspector/work-py39/dwave-inspector-0.4.0/dwave/inspector/utils.py", line 154, in wrapper
    return fn(*args, **kwargs)
  File "/usr/ports/science/py-dwave-inspector/work-py39/dwave-inspector-0.4.0/tests/test_proxies.py", line 67, in test_rewrite
    self.assertEqual(rewrite_url(url), f'proxy://{url}')
  File "/usr/ports/science/py-dwave-inspector/work-py39/dwave-inspector-0.4.0/dwave/inspector/proxies.py", line 74, in rewrite_url
    for rewriter in prioritized_url_rewriters():
  File "/usr/ports/science/py-dwave-inspector/work-py39/dwave-inspector-0.4.0/dwave/inspector/proxies.py", line 64, in prioritized_url_rewriters
    proxies = [ep.load() for ep in entry_points().select(group=entry_point_group['proxies'])]
  File "/usr/local/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 1019, in entry_points
    return SelectableGroups.load(eps).select(**params)
  File "/usr/local/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 472, in load
    ordered = sorted(eps, key=by_group)
  File "/usr/local/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 1016, in <genexpr>
    eps = itertools.chain.from_iterable(
  File "/usr/local/lib/python3.9/site-packages/importlib_metadata/_itertools.py", line 16, in unique_everseen
    k = key(element)
AttributeError: 'InMemoryDistribution' object has no attribute '_normalized_name'

======================================================================
ERROR: test_url_rewriters_prioritization (tests.test_proxies.TestProxies)
URL rewriters are correctly filtered and ordered (by desc priority).
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/ports/science/py-dwave-inspector/work-py39/dwave-inspector-0.4.0/dwave/inspector/utils.py", line 154, in wrapper
    return fn(*args, **kwargs)
  File "/usr/ports/science/py-dwave-inspector/work-py39/dwave-inspector-0.4.0/tests/test_proxies.py", line 50, in test_url_rewriters_prioritization
    pri = [v.priority for v in prioritized_url_rewriters()
  File "/usr/ports/science/py-dwave-inspector/work-py39/dwave-inspector-0.4.0/dwave/inspector/proxies.py", line 64, in prioritized_url_rewriters
    proxies = [ep.load() for ep in entry_points().select(group=entry_point_group['proxies'])]
  File "/usr/local/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 1019, in entry_points
    return SelectableGroups.load(eps).select(**params)
  File "/usr/local/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 472, in load
    ordered = sorted(eps, key=by_group)
  File "/usr/local/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 1016, in <genexpr>
    eps = itertools.chain.from_iterable(
  File "/usr/local/lib/python3.9/site-packages/importlib_metadata/_itertools.py", line 16, in unique_everseen
    k = key(element)
AttributeError: 'InMemoryDistribution' object has no attribute '_normalized_name'

======================================================================
```

Version: 0.4.0
Python-3.9
FreeBSD 13,1

**Comment by randomir** [comment]
Hi @yurivict, can you please share `pip freeze` output as well? Thanks!

**Comment by randomir** [comment]
Closing as stale.
